In [1]:
import pandas as pd
import sqlite3

data = "/Users/jose-cleiton/dev/script_pncp/data/resultado/2026-03-25/pncp_bart_test.db"

conn = sqlite3.connect(data)
resultado = pd.read_sql_query("SELECT * FROM contratacoes_filtradas", conn)
conn.close()

resultado.head()

,id,pncp_id,numero_controle,objeto_compra,prob_nao_relevante,prob_relevante,categoria,motivo,origem,criado_em
0,10,,,CREDENCIAMENTO DE PESSOA JURIDICA DE DIREITO P...,0.00248,0.99752,1,Nenhuma regra forte acionada,modelo_confiante,2026-03-26 13:18:17

In [10]:
import pandas as pd
import sqlite3

db_path = "/Users/jose-cleiton/dev/script_pncp/data/resultado/2026-03-25/pncp_filtrado_bart_1000.db"

with sqlite3.connect(db_path) as conn:
    resultado = pd.read_sql_query("SELECT * FROM contratacoes_filtradas", conn)

display(resultado.head())
print(resultado.shape)

,id,pncp_id,numero_controle,objeto_compra,prob_nao_relevante,prob_relevante,categoria,motivo,origem,criado_em
0,1,46523049000120-1-000021/2026,46523049000120-1-000021/2026,Contratação de empresa especializada para a pr...,0.000009,0.999991,1.0,Nenhuma regra forte acionada,modelo_confiante,2026-03-26 00:01:47
1,2,01131010000129-1-000009/2026,01131010000129-1-000009/2026,Contratação de serviços técnicos especializado...,0.000119,0.999881,1.0,Nenhuma regra forte acionada,modelo_confiante,2026-03-26 00:01:47
2,3,08870164000181-1-000011/2026,08870164000181-1-000011/2026,[Portal de Compras Públicas] - SISTEMA DE REGI...,0.000183,0.999817,0.0,Termos negativos fortes encontrados: frota,regra_forte_negativa,2026-03-26 00:01:47
3,4,08870164000181-1-000012/2026,08870164000181-1-000012/2026,[Portal de Compras Públicas] - AQUISIÇÃO PARCE...,0.000017,0.999983,1.0,Nenhuma regra forte acionada,modelo_confiante,2026-03-26 00:01:47
4,5,18404970000118-1-000006/2026,18404970000118-1-000006/2026,REGISTRO DE PREÇOS PARA FUTURA E EVENTUAL AQUI...,0.999961,0.000039,0.0,Termos negativos fortes encontrados: gêneros a...,regra_forte_negativa,2026-03-26 00:01:47

(1000, 10)

In [11]:
import pandas as pd
import sqlite3


query = """
SELECT objeto_compra, categoria, prob_relevante
FROM contratacoes_filtradas
"""

with sqlite3.connect(db_path) as conn:
    resultado = pd.read_sql_query(query, conn)

display(resultado.head())
print(resultado.shape)

                                       objeto_compra categoria  prob_relevante
0  Contratação de empresa especializada para a pr...       1.0        0.999991
1  Contratação de serviços técnicos especializado...       1.0        0.999881
2  [Portal de Compras Públicas] - SISTEMA DE REGI...       0.0        0.999817
3  [Portal de Compras Públicas] - AQUISIÇÃO PARCE...       1.0        0.999983
4  REGISTRO DE PREÇOS PARA FUTURA E EVENTUAL AQUI...       0.0        0.000039

(1000, 3)